name: CamelCase
description: Maurizio Turatti's Blog
meta_description: "Software Design and Architecture"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 9

baseurl: /
domain_name: 'http://www.maurizioturatti.com'
google_analytics: 'UA-43544427-1'

# Details for the RSS feed generator
url:            'http://www.maurizioturatti.com'
author:         'Maurizio Turatti'
